import type { IconName } from '../components/Icon'

export interface ParsedChangelogSection {
  id: string
  title: string
  subtitle: string
  details: string[]
  icon: IconName
  iconColor: string
  iconBg: string
  badge?: string
}

export interface ParsedRelease {
  version: string
  date: string
  sections: ParsedChangelogSection[]
}

/**
 * Embedded raw changelog markdown content - the root CHANGELOG.md's section for whichever version
 * is currently in apps/mobile/app.json's `expo.version`, copied in here because the mobile app has
 * no runtime access to a root-level file (there's no tested precedent in this codebase for
 * bundling one into the RN app at runtime).
 *
 * GENERATED - do not hand-edit this constant. It's regenerated by `pnpm sync-changelog`
 * (scripts/sync-changelog.mjs at the repo root), which reads CHANGELOG.md's `## [vX.Y.Z]` section
 * matching app.json's version and copies it in verbatim. To ship new release notes: add/update
 * that section in CHANGELOG.md, bump app.json's version to match, then run `pnpm sync-changelog`
 * from the repo root and commit the result.
 */
export const RAW_CHANGELOG_MD = `# Changelog

## [v0.3.0] - 2026-09-03

### ⛏️ Mining Studio Rework
- **Passage-Based Capture**: Captures whole passages (up to 1000 characters) instead of single sentences for batch generation.
- **Study & Mine Analysis**: One tap analyzes a passage into translation, CEFR-tailored grammar, and extracted vocabulary.
- **Whole-Card Tap & Bulk Cleanup**: Tap any passage to open it; select and clear multiple captures at once.

### 📚 Help Hub
- **New Help Hub**: Searchable in-app documentation with a chapter directory and a 2-minute video tour.
- **Fixed Disappearing Video Controls**: Fullscreen minimize/close buttons now reliably reappear on tap, not stuck invisible.
- **Fixed Wrong Video Playing**: Each chapter's video link now plays its own video, not always the same one.

### 🔔 Word of the Day Fixes
- **Daily Refresh That Actually Refreshes**: Regenerates on every app foreground, not just once per cold start.
- **Verified, Not Just Requested**: Retries automatically if the AI repeats a word already shown before.
- **Notification Opens the Right Popup**: Tapping the daily notification now opens the same summary card as Home.

### 💬 Feedback & Support
- **Public Email Warning**: Warns before submitting if your email will be visible in a public GitHub issue.
- **Fixed "Ask in Support" Link**: Was silently landing on the About page instead of the feedback form.

### 🤖 Redesigned AI Providers Screen
- **Card-Based Provider List**: Every provider now shows as its own card with clear Active/Enabled status.
- **Curated Model Profiles**: Pick from a curated model list per provider, each tagged with a speed/quality hint.
- **One-Tap Key Setup**: A "Get key" link opens each provider's developer portal directly, with cost guidance.
- **Enhanced Help**: Expanded help sections explain getting a key, and how Active/fallback provider selection works.
- **Reliable Activation**: Activating a provider now consistently enables it and simplifies how key presence is checked.

### 🎯 Review Mode Accuracy
- **Honest Review-Mode Badges**: Decks now show only the review formats they actually support, not always all five.
- **Cleaner Search Previews**: Removed review-mode badges from read-only Search previews where no saved card exists yet.
- **Shared Fallback Logic**: Deck review-mode defaults now come from one shared place across mobile and desktop.

### 🛠 AI Card Reliability
- **Visible Enrichment Failures**: A failed "Generate with AI" attempt now tells you it didn't complete.
- **Fixed Dead-End Retry Loops**: "Ask AI" and "More Info" no longer trap you in an unwinnable retry loop.
- **Smarter Edit Visibility**: Edit visibility is now tied to live generation state, not a one-time flag.

### 🧹 Review & Settings Cleanup
- **Decluttered Review Header**: Removed the estimated time-remaining pill and redundant review-mode badges from the review screen.
- **Removed Duplicate Audio Settings**: Deleted a duplicate "Audio Settings" entry that already existed elsewhere in Settings.
- **Card-Add Flows That Actually Close**: Adding a card now closes and shows a toast instead of stalling open.

### 🎴 Decks Screen Polish
- **Study-Progress Hero Link**: Decks hero now shows 30-day retention and links directly to Stats.
- **New Groq Model**: Added GPT-OSS 20B as a new curated option in the Groq model list.

### 🛠 Stability & Tooling
- **Fixed Cold-Boot Crash**: Installed a missing dependency that crashed every app launch on Expo SDK 57.
- **Expo SDK Alignment**: Synced all Expo package versions and dependencies to their SDK-57-matched releases.
- **Development Client Build Profile**: Added a dedicated EAS build profile for the Expo development client.
- **EAS Build Changelog Gate**: New confirmation prompt before every build, verifying changelog and version were updated.
`

function resolveIconAndColors(title: string): {
  icon: IconName
  iconColor: string
  iconBg: string
  badge?: string
} {
  const lower = title.toLowerCase()

  if (lower.includes('word of the day') || lower.includes('wotd')) {
    return { icon: 'Sparkles', iconColor: '#d97706', iconBg: '#fef3c7', badge: 'New' }
  }
  if (lower.includes('search') || lower.includes('lookup')) {
    return { icon: 'Search', iconColor: '#7c3aed', iconBg: '#f3e8ff' }
  }
  if (lower.includes('feedback') || lower.includes('support')) {
    return { icon: 'MessagesSquare', iconColor: '#0284c7', iconBg: '#e0f2fe' }
  }
  if (lower.includes('cloze') || lower.includes('practice') || lower.includes('review')) {
    return { icon: 'CheckCheck', iconColor: '#4f46e5', iconBg: '#e0e7ff' }
  }
  if (lower.includes('deck') || lower.includes('card')) {
    return { icon: 'Layers', iconColor: '#16a34a', iconBg: '#dcfce7' }
  }
  if (lower.includes('ai') || lower.includes('audio') || lower.includes('tts')) {
    return { icon: 'Volume2', iconColor: '#059669', iconBg: '#d1fae5' }
  }
  if (lower.includes('theme') || lower.includes('i18n') || lower.includes('icon')) {
    return { icon: 'Palette', iconColor: '#ea580c', iconBg: '#ffedd5' }
  }

  return { icon: 'Sparkles', iconColor: '#6366f1', iconBg: '#eef2ff' }
}

/**
 * Parses markdown changelog text into structured sections.
 */
export function parseChangelogMarkdown(markdown = RAW_CHANGELOG_MD): ParsedRelease {
  const lines = markdown.split('\n')
  let currentVersion = '0.2.0'
  let currentDate = ''
  const sections: ParsedChangelogSection[] = []

  let currentSection: ParsedChangelogSection | null = null

  for (const rawLine of lines) {
    const line = rawLine.trim()

    // Detect version header: e.g. ## [v0.2.0] - 2026-09-01 or ## v0.2.0
    const versionMatch = line.match(/^##\s+\[?(v?[\d\w.-]+)\]?\s*[-–]?\s*(.*)$/)
    if (versionMatch) {
      currentVersion = versionMatch[1] ?? '0.2.0'
      currentDate = versionMatch[2] ?? ''
      continue
    }

    // Detect feature section header: e.g. ### 🌟 Word of the Day & Daily Discovery
    const sectionMatch = line.match(/^###\s+(.*)$/)
    if (sectionMatch && sectionMatch[1]) {
      if (currentSection) {
        sections.push(currentSection)
      }

      const rawTitle = sectionMatch[1].replace(/^[^\w\s]+/, '').trim()
      const { icon, iconColor, iconBg, badge } = resolveIconAndColors(rawTitle)
      const id = rawTitle.toLowerCase().replace(/[^\w]+/g, '-')

      currentSection = {
        id,
        title: rawTitle,
        subtitle: '',
        details: [],
        icon,
        iconColor,
        iconBg,
        ...(badge ? { badge } : {}),
      }
      continue
    }

    // Detect bullet points: e.g. - **Title**: Description or - Description
    if (line.startsWith('-') || line.startsWith('*')) {
      const bulletText = line.replace(/^[-*]\s+/, '').trim()
      if (currentSection) {
        currentSection.details.push(bulletText)
        if (!currentSection.subtitle && bulletText) {
          // Use first bullet bold title as subtitle
          const boldMatch = bulletText.match(/\*\*([^*]+)\*\*/)
          if (boldMatch && boldMatch[1]) {
            currentSection.subtitle = boldMatch[1]
          }
        }
      }
    }
  }

  if (currentSection) {
    sections.push(currentSection)
  }

  return {
    version: currentVersion.replace(/^v/, ''),
    date: currentDate,
    sections,
  }
}
