import type { IconName } from '../components/Icon'

export interface ParsedChangelogSection {
  id: string
  title: string
  subtitle: string
  details: string[]
  icon: IconName
  iconColor: string
  iconBg: string
  badge?: string
}

export interface ParsedRelease {
  version: string
  date: string
  sections: ParsedChangelogSection[]
}

/**
 * Embedded raw changelog markdown content - the root CHANGELOG.md's section for whichever version
 * is currently in apps/mobile/app.json's `expo.version`, copied in here because the mobile app has
 * no runtime access to a root-level file (there's no tested precedent in this codebase for
 * bundling one into the RN app at runtime).
 *
 * GENERATED - do not hand-edit this constant. It's regenerated by `pnpm sync-changelog`
 * (scripts/sync-changelog.mjs at the repo root), which reads CHANGELOG.md's `## [vX.Y.Z]` section
 * matching app.json's version and copies it in verbatim. To ship new release notes: add/update
 * that section in CHANGELOG.md, bump app.json's version to match, then run `pnpm sync-changelog`
 * from the repo root and commit the result.
 */
export const RAW_CHANGELOG_MD = `# Changelog

## [v0.3.0] - 2026-09-02

### 🤖 Redesigned AI Providers Screen
- **Card-Based Provider List**: Every provider (OpenAI, Groq, Mistral, Gemini, Claude, DeepSeek) now shows as its own card with clear Active/Enabled status, instead of a flat settings list.
- **Curated Model Profiles**: Pick from a short, labeled list of real models per provider - each tagged with a speed/quality hint (e.g. Recommended, Fastest, Deep Nuance) and a one-line description, instead of typing a raw model name.
- **One-Tap Key Setup**: A "Get key from..." link on every card opens that provider's developer portal directly, plus new in-app guidance on free-tier vs pay-as-you-go options and roughly what a generated card costs.
- **Enhanced Help**: Expanded help sections explain how to get a key, and how the Active provider and automatic fallback between validated providers actually works.
- **Note**: this redesign was built alongside v0.2.0 but missed that release's actual build cut - this is its first real release.

### 🎯 Review Mode Accuracy
- **Honest Review-Mode Badges**: Decks now show only the review formats they actually support instead of always showing all five, even for older decks created before per-deck review modes existed.
- **Cleaner Search Previews**: Removed review-mode badges from read-only Search previews (Google Translate, Word Guide) where a saved card - and its review modes - doesn't exist yet.
- **Shared Fallback Logic**: Deck review-mode defaults are now computed in one shared place across mobile and desktop, so the two can no longer drift out of sync.

### 🛠 AI Card Reliability
- **Visible Enrichment Failures**: A "Generate with AI" attempt that fails partway now tells you it didn't complete, instead of silently leaving the card looking stuck with no explanation.
- **Fixed Dead-End Retry Loops**: "Ask AI" and "More Info" no longer open into an unwinnable retry loop on a card with no real meaning content yet - both now explain what's missing and point at Regenerate, on the word page and during Review alike.
- **Smarter Edit Visibility**: The Edit action on an AI-intended card is now tied to live generation state rather than a one-time navigation flag, so it no longer reappears unpredictably after a failed background enrichment.
`

function resolveIconAndColors(title: string): {
  icon: IconName
  iconColor: string
  iconBg: string
  badge?: string
} {
  const lower = title.toLowerCase()

  if (lower.includes('word of the day') || lower.includes('wotd')) {
    return { icon: 'Sparkles', iconColor: '#d97706', iconBg: '#fef3c7', badge: 'New' }
  }
  if (lower.includes('search') || lower.includes('lookup')) {
    return { icon: 'Search', iconColor: '#7c3aed', iconBg: '#f3e8ff' }
  }
  if (lower.includes('feedback') || lower.includes('support')) {
    return { icon: 'MessagesSquare', iconColor: '#0284c7', iconBg: '#e0f2fe' }
  }
  if (lower.includes('cloze') || lower.includes('practice') || lower.includes('review')) {
    return { icon: 'CheckCheck', iconColor: '#4f46e5', iconBg: '#e0e7ff' }
  }
  if (lower.includes('deck') || lower.includes('card')) {
    return { icon: 'Layers', iconColor: '#16a34a', iconBg: '#dcfce7' }
  }
  if (lower.includes('ai') || lower.includes('audio') || lower.includes('tts')) {
    return { icon: 'Volume2', iconColor: '#059669', iconBg: '#d1fae5' }
  }
  if (lower.includes('theme') || lower.includes('i18n') || lower.includes('icon')) {
    return { icon: 'Palette', iconColor: '#ea580c', iconBg: '#ffedd5' }
  }

  return { icon: 'Sparkles', iconColor: '#6366f1', iconBg: '#eef2ff' }
}

/**
 * Parses markdown changelog text into structured sections.
 */
export function parseChangelogMarkdown(markdown = RAW_CHANGELOG_MD): ParsedRelease {
  const lines = markdown.split('\n')
  let currentVersion = '0.2.0'
  let currentDate = ''
  const sections: ParsedChangelogSection[] = []

  let currentSection: ParsedChangelogSection | null = null

  for (const rawLine of lines) {
    const line = rawLine.trim()

    // Detect version header: e.g. ## [v0.2.0] - 2026-09-01 or ## v0.2.0
    const versionMatch = line.match(/^##\s+\[?(v?[\d\w.-]+)\]?\s*[-–]?\s*(.*)$/)
    if (versionMatch) {
      currentVersion = versionMatch[1] ?? '0.2.0'
      currentDate = versionMatch[2] ?? ''
      continue
    }

    // Detect feature section header: e.g. ### 🌟 Word of the Day & Daily Discovery
    const sectionMatch = line.match(/^###\s+(.*)$/)
    if (sectionMatch && sectionMatch[1]) {
      if (currentSection) {
        sections.push(currentSection)
      }

      const rawTitle = sectionMatch[1].replace(/^[^\w\s]+/, '').trim()
      const { icon, iconColor, iconBg, badge } = resolveIconAndColors(rawTitle)
      const id = rawTitle.toLowerCase().replace(/[^\w]+/g, '-')

      currentSection = {
        id,
        title: rawTitle,
        subtitle: '',
        details: [],
        icon,
        iconColor,
        iconBg,
        ...(badge ? { badge } : {}),
      }
      continue
    }

    // Detect bullet points: e.g. - **Title**: Description or - Description
    if (line.startsWith('-') || line.startsWith('*')) {
      const bulletText = line.replace(/^[-*]\s+/, '').trim()
      if (currentSection) {
        currentSection.details.push(bulletText)
        if (!currentSection.subtitle && bulletText) {
          // Use first bullet bold title as subtitle
          const boldMatch = bulletText.match(/\*\*([^*]+)\*\*/)
          if (boldMatch && boldMatch[1]) {
            currentSection.subtitle = boldMatch[1]
          }
        }
      }
    }
  }

  if (currentSection) {
    sections.push(currentSection)
  }

  return {
    version: currentVersion.replace(/^v/, ''),
    date: currentDate,
    sections,
  }
}
