plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.playinappupdate'
version = '1.0.0'

android {
  namespace "expo.modules.playinappupdate"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'com.google.android.play:app-update:2.1.0'
  implementation 'com.google.android.play:app-update-ktx:2.1.0'
}
