import type { JSX } from 'react'
import type { StyleProp, ViewStyle } from 'react-native'
import {
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Award,
  Bell,
  Book,
  BookOpen,
  Briefcase,
  Bug,
  ChartColumn,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleArrowUp,
  CircleCheck,
  CircleCheckBig,
  CircleDot,
  CirclePlus,
  CircleQuestionMark,
  CircleX,
  Clipboard,
  Clock,
  Cloud,
  CloudDownload,
  CloudOff,
  CloudUpload,
  Code,
  Coffee,
  CornerUpLeft,
  Cpu,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Flag,
  Flame,
  FolderOpen,
  GitCompare,
  GitMerge,
  Globe,
  GraduationCap,
  House,
  Image,
  Info,
  Key,
  Languages,
  Layers,
  LayoutGrid,
  Library,
  Lightbulb,
  List,
  Lock,
  MessageCircle,
  MessageSquare,
  MessageSquareText,
  MessagesSquare,
  Mic,
  Newspaper,
  Palette,
  Pencil,
  Plane,
  Play,
  Plus,
  Puzzle,
  Radio,
  Redo2,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Shuffle,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  SquareCheck,
  SquarePen,
  Star,
  Tag,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  Trophy,
  Tv,
  Type as TypeIcon,
  Undo2,
  User,
  Video,
  Volume1,
  Volume2,
  WandSparkles,
  Wrench,
  X,
  Zap,
  type LucideProps,
} from 'lucide-react-native'
import { DeepSeekIcon, GroqIcon } from './BrandIcons'

/**
 * The app's single icon set, migrated from Ionicons (@expo/vector-icons) to Lucide so mobile and
 * desktop (which already uses lucide-react) share the exact same icon names and visual design —
 * a name string picked in packages/core (TEMPLATE_VARIABLES, PROVIDER_META_DATA, help-section
 * data, etc.) now means the same glyph on both platforms, resolved through each platform's own
 * lucide package (lucide-react-native here, lucide-react on desktop) rather than needing a
 * per-platform translation table.
 *
 * One resolver component (rather than importing a different named component at every call site)
 * because most icon usages in this app are already data-driven by a string (help sections, the
 * bottom tab bar, provider/template/question-type metadata, search results) — matching the shape
 * `<Ionicons name={dynamicString} />` already had, just swapping the icon set underneath.
 *
 * Only the ~90 icons this app actually uses are imported by name (not Lucide's full ~1700-icon
 * set), so the bundle only pays for what's drawn.
 */
const ICONS = {
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Award,
  Bell,
  Book,
  BookOpen,
  Briefcase,
  Bug,
  ChartColumn,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleArrowUp,
  CircleCheck,
  CircleCheckBig,
  CircleDot,
  CirclePlus,
  CircleQuestionMark,
  CircleX,
  Clipboard,
  Clock,
  Cloud,
  CloudDownload,
  CloudOff,
  CloudUpload,
  Code,
  Coffee,
  CornerUpLeft,
  Cpu,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Flag,
  Flame,
  FolderOpen,
  GitCompare,
  GitMerge,
  Globe,
  GraduationCap,
  House,
  Image,
  Info,
  Key,
  Languages,
  Layers,
  LayoutGrid,
  Library,
  Lightbulb,
  List,
  Lock,
  MessageCircle,
  MessageSquare,
  MessageSquareText,
  MessagesSquare,
  Mic,
  Newspaper,
  Palette,
  Pencil,
  Plane,
  Play,
  Plus,
  Puzzle,
  Radio,
  Redo2,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Shuffle,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  SquareCheck,
  SquarePen,
  Star,
  Tag,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  Trophy,
  Tv,
  Type: TypeIcon,
  Undo2,
  User,
  Video,
  Volume1,
  Volume2,
  WandSparkles,
  Wrench,
  X,
  Zap,
  DeepSeek: DeepSeekIcon,
  Groq: GroqIcon,
} as const

export type IconName = keyof typeof ICONS

/** True for any string this app's icon set can render — the same runtime check the old
 * `keyof typeof Ionicons.glyphMap` cast sites relied on the type system alone for. */
export function isIconName(name: string): name is IconName {
  return name in ICONS
}

export function Icon(props: {
  name: IconName
  size?: number
  color?: string
  style?: StyleProp<ViewStyle>
  strokeWidth?: LucideProps['strokeWidth']
  accessibilityLabel?: string
}): JSX.Element {
  const Component = isIconName(props.name) ? ICONS[props.name] : CircleAlert
  return (
    <Component
      size={props.size ?? 24}
      style={props.style}
      {...(props.color !== undefined && { color: props.color })}
      {...(props.strokeWidth !== undefined && { strokeWidth: props.strokeWidth })}
      {...(props.accessibilityLabel !== undefined && { accessibilityLabel: props.accessibilityLabel })}
    />
  )
}
